/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  AppUsers: () => import('#controllers/app_users_controller'),
  Attachments: () => import('#controllers/attachments_controller'),
  AuditLogs: () => import('#controllers/audit_logs_controller'),
  CropTypes: () => import('#controllers/crop_types_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Devices: () => import('#controllers/devices_controller'),
  EmailVerification: () => import('#controllers/email_verification_controller'),
  Farmers: () => import('#controllers/farmers_controller'),
  Imports: () => import('#controllers/imports_controller'),
  Monetization: () => import('#controllers/monetization_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Observations: () => import('#controllers/observations_controller'),
  Organizations: () => import('#controllers/organizations_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Plots: () => import('#controllers/plots_controller'),
  Predictions: () => import('#controllers/predictions_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Rag: () => import('#controllers/rag_controller'),
  SyncQueue: () => import('#controllers/sync_queue_controller'),
}
