/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppUserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'organizationId', 'passwordHash', 'phone', 'role', 'updatedAt'] as const
  $columns = AppUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare organizationId: string | null
  @column()
  declare passwordHash: string | null
  @column()
  declare phone: string | null
  @column()
  declare role: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AttachmentSchema extends BaseModel {
  static $columns = ['caption', 'clientCreatedAt', 'createdAt', 'deviceId', 'fileSizeBytes', 'fileType', 'fileUrl', 'id', 'observationId', 'uploadedBy'] as const
  $columns = AttachmentSchema.$columns
  @column()
  declare caption: string | null
  @column.dateTime()
  declare clientCreatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deviceId: string | null
  @column()
  declare fileSizeBytes: number | null
  @column()
  declare fileType: string | null
  @column()
  declare fileUrl: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare observationId: string | null
  @column()
  declare uploadedBy: string
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'id', 'ipAddress', 'newValues', 'oldValues', 'recordId', 'tableName', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare recordId: string
  @column()
  declare tableName: string
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CropTypeSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'id', 'localName', 'name'] as const
  $columns = CropTypeSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare localName: string | null
  @column()
  declare name: string
}

export class DatasetPermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'datasetId', 'datasetType', 'expiresAt', 'grantedBy', 'id', 'permissions', 'updatedAt', 'userId'] as const
  $columns = DatasetPermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare datasetId: string | null
  @column()
  declare datasetType: string
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare grantedBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare permissions: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class DeviceSchema extends BaseModel {
  static $columns = ['createdAt', 'deviceName', 'deviceUuid', 'id', 'lastSyncAt', 'userId'] as const
  $columns = DeviceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deviceName: string | null
  @column()
  declare deviceUuid: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastSyncAt: DateTime | null
  @column()
  declare userId: string
}

export class FarmerSchema extends BaseModel {
  static $columns = ['clientCreatedAt', 'clientUpdatedAt', 'createdAt', 'createdBy', 'deletedAt', 'deviceId', 'fullName', 'householdSize', 'id', 'locationRegion', 'locationWoreda', 'locationZone', 'notes', 'organizationId', 'phone', 'updatedAt'] as const
  $columns = FarmerSchema.$columns
  @column.dateTime()
  declare clientCreatedAt: DateTime | null
  @column.dateTime()
  declare clientUpdatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deviceId: string | null
  @column()
  declare fullName: string
  @column()
  declare householdSize: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare locationRegion: string | null
  @column()
  declare locationWoreda: string | null
  @column()
  declare locationZone: string | null
  @column()
  declare notes: string | null
  @column()
  declare organizationId: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ImportJobSchema extends BaseModel {
  static $columns = ['completedAt', 'createdAt', 'createdBy', 'errorMessage', 'fileName', 'fileSizeBytes', 'fileType', 'id', 'importedRows', 'schemaMapping', 'skippedRows', 'startedAt', 'status', 'totalRows', 'updatedAt', 'validationErrors'] as const
  $columns = ImportJobSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string | null
  @column()
  declare errorMessage: string | null
  @column()
  declare fileName: string
  @column()
  declare fileSizeBytes: bigint | number | null
  @column()
  declare fileType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importedRows: number | null
  @column()
  declare schemaMapping: any | null
  @column()
  declare skippedRows: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: any
  @column()
  declare totalRows: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare validationErrors: any | null
}

export class ImportedRecordSchema extends BaseModel {
  static $columns = ['actualYieldKg', 'areaHectares', 'createdAt', 'cropCategory', 'cropName', 'expectedYieldKg', 'fertilizerAmountKg', 'fertilizerType', 'harvestDate', 'id', 'importJobId', 'irrigationType', 'kebele', 'pesticideUsed', 'plantingDate', 'rainfallMm', 'rawValues', 'region', 'season', 'soilType', 'sourceRow', 'status', 'temperatureCelsius', 'validationErrors', 'year'] as const
  $columns = ImportedRecordSchema.$columns
  @column()
  declare actualYieldKg: string | null
  @column()
  declare areaHectares: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cropCategory: string | null
  @column()
  declare cropName: string | null
  @column()
  declare expectedYieldKg: string | null
  @column()
  declare fertilizerAmountKg: string | null
  @column()
  declare fertilizerType: string | null
  @column.date()
  declare harvestDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importJobId: string
  @column()
  declare irrigationType: string | null
  @column()
  declare kebele: string | null
  @column()
  declare pesticideUsed: string | null
  @column.date()
  declare plantingDate: DateTime | null
  @column()
  declare rainfallMm: string | null
  @column()
  declare rawValues: any | null
  @column()
  declare region: string | null
  @column()
  declare season: string | null
  @column()
  declare soilType: string | null
  @column()
  declare sourceRow: number
  @column()
  declare status: any
  @column()
  declare temperatureCelsius: string | null
  @column()
  declare validationErrors: any | null
  @column()
  declare year: number | null
}

export class ObservationSchema extends BaseModel {
  static $columns = ['actualYieldKg', 'clientCreatedAt', 'clientUpdatedAt', 'createdAt', 'createdBy', 'cropTypeId', 'deletedAt', 'deviceId', 'expectedYieldKg', 'fertilizerUsed', 'growthStage', 'healthStatus', 'id', 'metadata', 'notes', 'pestIssues', 'plantingDate', 'plotId', 'updatedAt', 'version', 'yieldEstimateDate'] as const
  $columns = ObservationSchema.$columns
  @column()
  declare actualYieldKg: string | null
  @column.dateTime()
  declare clientCreatedAt: DateTime | null
  @column.dateTime()
  declare clientUpdatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string
  @column()
  declare cropTypeId: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deviceId: string | null
  @column()
  declare expectedYieldKg: string | null
  @column()
  declare fertilizerUsed: boolean | null
  @column()
  declare growthStage: string | null
  @column()
  declare healthStatus: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any | null
  @column()
  declare notes: string | null
  @column()
  declare pestIssues: string | null
  @column.date()
  declare plantingDate: DateTime | null
  @column()
  declare plotId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number | null
  @column.date()
  declare yieldEstimateDate: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['contactPhone', 'createdAt', 'id', 'name', 'region', 'type', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare contactPhone: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare region: string | null
  @column()
  declare type: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlotSchema extends BaseModel {
  static $columns = ['altitude', 'areaLocal', 'areaSqm', 'clientCreatedAt', 'clientUpdatedAt', 'createdAt', 'createdBy', 'deletedAt', 'deviceId', 'farmerId', 'id', 'irrigation', 'latitude', 'longitude', 'plotName', 'soilType', 'updatedAt', 'version'] as const
  $columns = PlotSchema.$columns
  @column()
  declare altitude: string | null
  @column()
  declare areaLocal: string | null
  @column()
  declare areaSqm: string | null
  @column.dateTime()
  declare clientCreatedAt: DateTime | null
  @column.dateTime()
  declare clientUpdatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare deviceId: string | null
  @column()
  declare farmerId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare irrigation: boolean | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare plotName: string | null
  @column()
  declare soilType: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number | null
}

export class PredictionSchema extends BaseModel {
  static $columns = ['confidenceScore', 'createdAt', 'errorMessage', 'id', 'importJobId', 'importedRecordId', 'inputFeatures', 'modelType', 'modelVersion', 'predictedYieldKg', 'rawOutput', 'requestedBy', 'status', 'updatedAt'] as const
  $columns = PredictionSchema.$columns
  @column()
  declare confidenceScore: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importJobId: string | null
  @column()
  declare importedRecordId: string | null
  @column()
  declare inputFeatures: any
  @column()
  declare modelType: string
  @column()
  declare modelVersion: string
  @column()
  declare predictedYieldKg: string | null
  @column()
  declare rawOutput: any | null
  @column()
  declare requestedBy: string | null
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'metadata', 'name', 'priceUsd', 'productType', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare metadata: any | null
  @column()
  declare name: string
  @column()
  declare priceUsd: string
  @column()
  declare productType: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'productId', 'startsAt', 'status', 'updatedAt', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SyncQueueSchema extends BaseModel {
  static $columns = ['batchId', 'clientTimestamp', 'createdAt', 'deviceId', 'entityId', 'entityType', 'errorMessage', 'id', 'operation', 'payload', 'processedAt', 'resolvedAt', 'retryCount', 'serverTimestamp', 'status', 'userId'] as const
  $columns = SyncQueueSchema.$columns
  @column()
  declare batchId: string
  @column.dateTime()
  declare clientTimestamp: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deviceId: string
  @column()
  declare entityId: string | null
  @column()
  declare entityType: string
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare operation: string
  @column()
  declare payload: any
  @column.dateTime()
  declare processedAt: DateTime | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare retryCount: number | null
  @column.dateTime()
  declare serverTimestamp: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare userId: string
}

export class TransactionSchema extends BaseModel {
  static $columns = ['amountUsd', 'createdAt', 'currency', 'id', 'paymentMetadata', 'paymentProvider', 'paymentReference', 'productId', 'status', 'subscriptionId', 'updatedAt', 'userId'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare amountUsd: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare paymentMetadata: any | null
  @column()
  declare paymentProvider: string | null
  @column()
  declare paymentReference: string | null
  @column()
  declare productId: string | null
  @column()
  declare status: any
  @column()
  declare subscriptionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
