/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.new_account.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/signup',
    tokens: [{"old":"/api/v1/auth/signup","type":0,"val":"api","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['auth.new_account.store']['types'],
  },
  'auth.access_token.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.access_token.store']['types'],
  },
  'auth.access_token.refresh': {
    methods: ["POST"],
    pattern: '/api/v1/auth/refresh',
    tokens: [{"old":"/api/v1/auth/refresh","type":0,"val":"api","end":""},{"old":"/api/v1/auth/refresh","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/refresh","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/refresh","type":0,"val":"refresh","end":""}],
    types: placeholder as Registry['auth.access_token.refresh']['types'],
  },
  'auth.access_token.destroy': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.access_token.destroy']['types'],
  },
  'auth.access_token.destroy_all': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout-all',
    tokens: [{"old":"/api/v1/auth/logout-all","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout-all","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout-all","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout-all","type":0,"val":"logout-all","end":""}],
    types: placeholder as Registry['auth.access_token.destroy_all']['types'],
  },
  'auth.access_token.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/tokens',
    tokens: [{"old":"/api/v1/auth/tokens","type":0,"val":"api","end":""},{"old":"/api/v1/auth/tokens","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/tokens","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/tokens","type":0,"val":"tokens","end":""}],
    types: placeholder as Registry['auth.access_token.index']['types'],
  },
  'auth.access_token.revoke': {
    methods: ["DELETE"],
    pattern: '/api/v1/auth/tokens/:tokenId',
    tokens: [{"old":"/api/v1/auth/tokens/:tokenId","type":0,"val":"api","end":""},{"old":"/api/v1/auth/tokens/:tokenId","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/tokens/:tokenId","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/tokens/:tokenId","type":0,"val":"tokens","end":""},{"old":"/api/v1/auth/tokens/:tokenId","type":1,"val":"tokenId","end":""}],
    types: placeholder as Registry['auth.access_token.revoke']['types'],
  },
  'auth.password_reset.forgot': {
    methods: ["POST"],
    pattern: '/api/v1/auth/password/forgot',
    tokens: [{"old":"/api/v1/auth/password/forgot","type":0,"val":"api","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"password","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"forgot","end":""}],
    types: placeholder as Registry['auth.password_reset.forgot']['types'],
  },
  'auth.password_reset.reset': {
    methods: ["POST"],
    pattern: '/api/v1/auth/password/reset',
    tokens: [{"old":"/api/v1/auth/password/reset","type":0,"val":"api","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"password","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"reset","end":""}],
    types: placeholder as Registry['auth.password_reset.reset']['types'],
  },
  'auth.email_verification.send': {
    methods: ["POST"],
    pattern: '/api/v1/auth/email/verification-notification',
    tokens: [{"old":"/api/v1/auth/email/verification-notification","type":0,"val":"api","end":""},{"old":"/api/v1/auth/email/verification-notification","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/email/verification-notification","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/email/verification-notification","type":0,"val":"email","end":""},{"old":"/api/v1/auth/email/verification-notification","type":0,"val":"verification-notification","end":""}],
    types: placeholder as Registry['auth.email_verification.send']['types'],
  },
  'auth.email_verification.verify': {
    methods: ["POST"],
    pattern: '/api/v1/auth/email/verify',
    tokens: [{"old":"/api/v1/auth/email/verify","type":0,"val":"api","end":""},{"old":"/api/v1/auth/email/verify","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/email/verify","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/email/verify","type":0,"val":"email","end":""},{"old":"/api/v1/auth/email/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['auth.email_verification.verify']['types'],
  },
  'profile.profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.profile.show']['types'],
  },
  'profile.profile.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.profile.update']['types'],
  },
  'profile.profile.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.profile.destroy']['types'],
  },
  'dashboard.dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard',
    tokens: [{"old":"/api/v1/dashboard","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.dashboard.index']['types'],
  },
  'dashboard.dashboard.farmer_counts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/farmer-counts',
    tokens: [{"old":"/api/v1/dashboard/farmer-counts","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/farmer-counts","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/farmer-counts","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/farmer-counts","type":0,"val":"farmer-counts","end":""}],
    types: placeholder as Registry['dashboard.dashboard.farmer_counts']['types'],
  },
  'dashboard.dashboard.yield_summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/yield-summary',
    tokens: [{"old":"/api/v1/dashboard/yield-summary","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/yield-summary","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/yield-summary","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/yield-summary","type":0,"val":"yield-summary","end":""}],
    types: placeholder as Registry['dashboard.dashboard.yield_summary']['types'],
  },
  'dashboard.dashboard.sync_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/sync-status',
    tokens: [{"old":"/api/v1/dashboard/sync-status","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/sync-status","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/sync-status","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/sync-status","type":0,"val":"sync-status","end":""}],
    types: placeholder as Registry['dashboard.dashboard.sync_status']['types'],
  },
  'dashboard.dashboard.health': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/health',
    tokens: [{"old":"/api/v1/dashboard/health","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/health","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/health","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/health","type":0,"val":"health","end":""}],
    types: placeholder as Registry['dashboard.dashboard.health']['types'],
  },
  'organizations.organizations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/organizations',
    tokens: [{"old":"/api/v1/organizations","type":0,"val":"api","end":""},{"old":"/api/v1/organizations","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations","type":0,"val":"organizations","end":""}],
    types: placeholder as Registry['organizations.organizations.index']['types'],
  },
  'organizations.organizations.store': {
    methods: ["POST"],
    pattern: '/api/v1/organizations',
    tokens: [{"old":"/api/v1/organizations","type":0,"val":"api","end":""},{"old":"/api/v1/organizations","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations","type":0,"val":"organizations","end":""}],
    types: placeholder as Registry['organizations.organizations.store']['types'],
  },
  'organizations.organizations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/organizations/:id',
    tokens: [{"old":"/api/v1/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.organizations.show']['types'],
  },
  'organizations.organizations.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/organizations/:id',
    tokens: [{"old":"/api/v1/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.organizations.update']['types'],
  },
  'organizations.organizations.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/organizations/:id',
    tokens: [{"old":"/api/v1/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.organizations.destroy']['types'],
  },
  'organizations.organizations.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/organizations/:id/dashboard',
    tokens: [{"old":"/api/v1/organizations/:id/dashboard","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id/dashboard","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id/dashboard","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id/dashboard","type":1,"val":"id","end":""},{"old":"/api/v1/organizations/:id/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['organizations.organizations.dashboard']['types'],
  },
  'appUsers.app_users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/app-users',
    tokens: [{"old":"/api/v1/app-users","type":0,"val":"api","end":""},{"old":"/api/v1/app-users","type":0,"val":"v1","end":""},{"old":"/api/v1/app-users","type":0,"val":"app-users","end":""}],
    types: placeholder as Registry['appUsers.app_users.index']['types'],
  },
  'appUsers.app_users.store': {
    methods: ["POST"],
    pattern: '/api/v1/app-users',
    tokens: [{"old":"/api/v1/app-users","type":0,"val":"api","end":""},{"old":"/api/v1/app-users","type":0,"val":"v1","end":""},{"old":"/api/v1/app-users","type":0,"val":"app-users","end":""}],
    types: placeholder as Registry['appUsers.app_users.store']['types'],
  },
  'appUsers.app_users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/app-users/:id',
    tokens: [{"old":"/api/v1/app-users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/app-users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/app-users/:id","type":0,"val":"app-users","end":""},{"old":"/api/v1/app-users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['appUsers.app_users.show']['types'],
  },
  'appUsers.app_users.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/app-users/:id',
    tokens: [{"old":"/api/v1/app-users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/app-users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/app-users/:id","type":0,"val":"app-users","end":""},{"old":"/api/v1/app-users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['appUsers.app_users.update']['types'],
  },
  'appUsers.app_users.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/app-users/:id',
    tokens: [{"old":"/api/v1/app-users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/app-users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/app-users/:id","type":0,"val":"app-users","end":""},{"old":"/api/v1/app-users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['appUsers.app_users.destroy']['types'],
  },
  'appUsers.app_users.activate': {
    methods: ["PATCH"],
    pattern: '/api/v1/app-users/:id/activate',
    tokens: [{"old":"/api/v1/app-users/:id/activate","type":0,"val":"api","end":""},{"old":"/api/v1/app-users/:id/activate","type":0,"val":"v1","end":""},{"old":"/api/v1/app-users/:id/activate","type":0,"val":"app-users","end":""},{"old":"/api/v1/app-users/:id/activate","type":1,"val":"id","end":""},{"old":"/api/v1/app-users/:id/activate","type":0,"val":"activate","end":""}],
    types: placeholder as Registry['appUsers.app_users.activate']['types'],
  },
  'appUsers.app_users.devices': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/app-users/:id/devices',
    tokens: [{"old":"/api/v1/app-users/:id/devices","type":0,"val":"api","end":""},{"old":"/api/v1/app-users/:id/devices","type":0,"val":"v1","end":""},{"old":"/api/v1/app-users/:id/devices","type":0,"val":"app-users","end":""},{"old":"/api/v1/app-users/:id/devices","type":1,"val":"id","end":""},{"old":"/api/v1/app-users/:id/devices","type":0,"val":"devices","end":""}],
    types: placeholder as Registry['appUsers.app_users.devices']['types'],
  },
  'devices.devices.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/devices',
    tokens: [{"old":"/api/v1/devices","type":0,"val":"api","end":""},{"old":"/api/v1/devices","type":0,"val":"v1","end":""},{"old":"/api/v1/devices","type":0,"val":"devices","end":""}],
    types: placeholder as Registry['devices.devices.index']['types'],
  },
  'devices.devices.store': {
    methods: ["POST"],
    pattern: '/api/v1/devices',
    tokens: [{"old":"/api/v1/devices","type":0,"val":"api","end":""},{"old":"/api/v1/devices","type":0,"val":"v1","end":""},{"old":"/api/v1/devices","type":0,"val":"devices","end":""}],
    types: placeholder as Registry['devices.devices.store']['types'],
  },
  'devices.devices.show_by_uuid': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/devices/by-uuid/:deviceUuid',
    tokens: [{"old":"/api/v1/devices/by-uuid/:deviceUuid","type":0,"val":"api","end":""},{"old":"/api/v1/devices/by-uuid/:deviceUuid","type":0,"val":"v1","end":""},{"old":"/api/v1/devices/by-uuid/:deviceUuid","type":0,"val":"devices","end":""},{"old":"/api/v1/devices/by-uuid/:deviceUuid","type":0,"val":"by-uuid","end":""},{"old":"/api/v1/devices/by-uuid/:deviceUuid","type":1,"val":"deviceUuid","end":""}],
    types: placeholder as Registry['devices.devices.show_by_uuid']['types'],
  },
  'devices.devices.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/devices/:id',
    tokens: [{"old":"/api/v1/devices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/devices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/devices/:id","type":0,"val":"devices","end":""},{"old":"/api/v1/devices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['devices.devices.show']['types'],
  },
  'devices.devices.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/devices/:id',
    tokens: [{"old":"/api/v1/devices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/devices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/devices/:id","type":0,"val":"devices","end":""},{"old":"/api/v1/devices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['devices.devices.update']['types'],
  },
  'devices.devices.mark_synced': {
    methods: ["PATCH"],
    pattern: '/api/v1/devices/:id/sync',
    tokens: [{"old":"/api/v1/devices/:id/sync","type":0,"val":"api","end":""},{"old":"/api/v1/devices/:id/sync","type":0,"val":"v1","end":""},{"old":"/api/v1/devices/:id/sync","type":0,"val":"devices","end":""},{"old":"/api/v1/devices/:id/sync","type":1,"val":"id","end":""},{"old":"/api/v1/devices/:id/sync","type":0,"val":"sync","end":""}],
    types: placeholder as Registry['devices.devices.mark_synced']['types'],
  },
  'devices.devices.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/devices/:id',
    tokens: [{"old":"/api/v1/devices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/devices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/devices/:id","type":0,"val":"devices","end":""},{"old":"/api/v1/devices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['devices.devices.destroy']['types'],
  },
  'cropTypes.crop_types.categories': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/crop-types/categories',
    tokens: [{"old":"/api/v1/crop-types/categories","type":0,"val":"api","end":""},{"old":"/api/v1/crop-types/categories","type":0,"val":"v1","end":""},{"old":"/api/v1/crop-types/categories","type":0,"val":"crop-types","end":""},{"old":"/api/v1/crop-types/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['cropTypes.crop_types.categories']['types'],
  },
  'cropTypes.crop_types.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/crop-types',
    tokens: [{"old":"/api/v1/crop-types","type":0,"val":"api","end":""},{"old":"/api/v1/crop-types","type":0,"val":"v1","end":""},{"old":"/api/v1/crop-types","type":0,"val":"crop-types","end":""}],
    types: placeholder as Registry['cropTypes.crop_types.index']['types'],
  },
  'cropTypes.crop_types.store': {
    methods: ["POST"],
    pattern: '/api/v1/crop-types',
    tokens: [{"old":"/api/v1/crop-types","type":0,"val":"api","end":""},{"old":"/api/v1/crop-types","type":0,"val":"v1","end":""},{"old":"/api/v1/crop-types","type":0,"val":"crop-types","end":""}],
    types: placeholder as Registry['cropTypes.crop_types.store']['types'],
  },
  'cropTypes.crop_types.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/crop-types/:id',
    tokens: [{"old":"/api/v1/crop-types/:id","type":0,"val":"api","end":""},{"old":"/api/v1/crop-types/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/crop-types/:id","type":0,"val":"crop-types","end":""},{"old":"/api/v1/crop-types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cropTypes.crop_types.show']['types'],
  },
  'cropTypes.crop_types.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/crop-types/:id',
    tokens: [{"old":"/api/v1/crop-types/:id","type":0,"val":"api","end":""},{"old":"/api/v1/crop-types/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/crop-types/:id","type":0,"val":"crop-types","end":""},{"old":"/api/v1/crop-types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cropTypes.crop_types.update']['types'],
  },
  'cropTypes.crop_types.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/crop-types/:id',
    tokens: [{"old":"/api/v1/crop-types/:id","type":0,"val":"api","end":""},{"old":"/api/v1/crop-types/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/crop-types/:id","type":0,"val":"crop-types","end":""},{"old":"/api/v1/crop-types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cropTypes.crop_types.destroy']['types'],
  },
  'farmers.farmers.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/farmers/stats',
    tokens: [{"old":"/api/v1/farmers/stats","type":0,"val":"api","end":""},{"old":"/api/v1/farmers/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers/stats","type":0,"val":"farmers","end":""},{"old":"/api/v1/farmers/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['farmers.farmers.stats']['types'],
  },
  'farmers.farmers.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/farmers',
    tokens: [{"old":"/api/v1/farmers","type":0,"val":"api","end":""},{"old":"/api/v1/farmers","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers","type":0,"val":"farmers","end":""}],
    types: placeholder as Registry['farmers.farmers.index']['types'],
  },
  'farmers.farmers.store': {
    methods: ["POST"],
    pattern: '/api/v1/farmers',
    tokens: [{"old":"/api/v1/farmers","type":0,"val":"api","end":""},{"old":"/api/v1/farmers","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers","type":0,"val":"farmers","end":""}],
    types: placeholder as Registry['farmers.farmers.store']['types'],
  },
  'farmers.farmers.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/farmers/:id',
    tokens: [{"old":"/api/v1/farmers/:id","type":0,"val":"api","end":""},{"old":"/api/v1/farmers/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers/:id","type":0,"val":"farmers","end":""},{"old":"/api/v1/farmers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['farmers.farmers.show']['types'],
  },
  'farmers.farmers.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/farmers/:id',
    tokens: [{"old":"/api/v1/farmers/:id","type":0,"val":"api","end":""},{"old":"/api/v1/farmers/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers/:id","type":0,"val":"farmers","end":""},{"old":"/api/v1/farmers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['farmers.farmers.update']['types'],
  },
  'farmers.farmers.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/farmers/:id',
    tokens: [{"old":"/api/v1/farmers/:id","type":0,"val":"api","end":""},{"old":"/api/v1/farmers/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers/:id","type":0,"val":"farmers","end":""},{"old":"/api/v1/farmers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['farmers.farmers.destroy']['types'],
  },
  'farmers.farmers.restore': {
    methods: ["POST"],
    pattern: '/api/v1/farmers/:id/restore',
    tokens: [{"old":"/api/v1/farmers/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/farmers/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers/:id/restore","type":0,"val":"farmers","end":""},{"old":"/api/v1/farmers/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/farmers/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['farmers.farmers.restore']['types'],
  },
  'farmers.farmers.plots': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/farmers/:id/plots',
    tokens: [{"old":"/api/v1/farmers/:id/plots","type":0,"val":"api","end":""},{"old":"/api/v1/farmers/:id/plots","type":0,"val":"v1","end":""},{"old":"/api/v1/farmers/:id/plots","type":0,"val":"farmers","end":""},{"old":"/api/v1/farmers/:id/plots","type":1,"val":"id","end":""},{"old":"/api/v1/farmers/:id/plots","type":0,"val":"plots","end":""}],
    types: placeholder as Registry['farmers.farmers.plots']['types'],
  },
  'plots.plots.nearby': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/plots/nearby',
    tokens: [{"old":"/api/v1/plots/nearby","type":0,"val":"api","end":""},{"old":"/api/v1/plots/nearby","type":0,"val":"v1","end":""},{"old":"/api/v1/plots/nearby","type":0,"val":"plots","end":""},{"old":"/api/v1/plots/nearby","type":0,"val":"nearby","end":""}],
    types: placeholder as Registry['plots.plots.nearby']['types'],
  },
  'plots.plots.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/plots',
    tokens: [{"old":"/api/v1/plots","type":0,"val":"api","end":""},{"old":"/api/v1/plots","type":0,"val":"v1","end":""},{"old":"/api/v1/plots","type":0,"val":"plots","end":""}],
    types: placeholder as Registry['plots.plots.index']['types'],
  },
  'plots.plots.store': {
    methods: ["POST"],
    pattern: '/api/v1/plots',
    tokens: [{"old":"/api/v1/plots","type":0,"val":"api","end":""},{"old":"/api/v1/plots","type":0,"val":"v1","end":""},{"old":"/api/v1/plots","type":0,"val":"plots","end":""}],
    types: placeholder as Registry['plots.plots.store']['types'],
  },
  'plots.plots.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/plots/:id',
    tokens: [{"old":"/api/v1/plots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/plots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/plots/:id","type":0,"val":"plots","end":""},{"old":"/api/v1/plots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['plots.plots.show']['types'],
  },
  'plots.plots.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/plots/:id',
    tokens: [{"old":"/api/v1/plots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/plots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/plots/:id","type":0,"val":"plots","end":""},{"old":"/api/v1/plots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['plots.plots.update']['types'],
  },
  'plots.plots.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/plots/:id',
    tokens: [{"old":"/api/v1/plots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/plots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/plots/:id","type":0,"val":"plots","end":""},{"old":"/api/v1/plots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['plots.plots.destroy']['types'],
  },
  'plots.plots.restore': {
    methods: ["POST"],
    pattern: '/api/v1/plots/:id/restore',
    tokens: [{"old":"/api/v1/plots/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/plots/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/plots/:id/restore","type":0,"val":"plots","end":""},{"old":"/api/v1/plots/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/plots/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['plots.plots.restore']['types'],
  },
  'observations.observations.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/observations/summary',
    tokens: [{"old":"/api/v1/observations/summary","type":0,"val":"api","end":""},{"old":"/api/v1/observations/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/observations/summary","type":0,"val":"observations","end":""},{"old":"/api/v1/observations/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['observations.observations.summary']['types'],
  },
  'observations.observations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/observations',
    tokens: [{"old":"/api/v1/observations","type":0,"val":"api","end":""},{"old":"/api/v1/observations","type":0,"val":"v1","end":""},{"old":"/api/v1/observations","type":0,"val":"observations","end":""}],
    types: placeholder as Registry['observations.observations.index']['types'],
  },
  'observations.observations.store': {
    methods: ["POST"],
    pattern: '/api/v1/observations',
    tokens: [{"old":"/api/v1/observations","type":0,"val":"api","end":""},{"old":"/api/v1/observations","type":0,"val":"v1","end":""},{"old":"/api/v1/observations","type":0,"val":"observations","end":""}],
    types: placeholder as Registry['observations.observations.store']['types'],
  },
  'observations.observations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/observations/:id',
    tokens: [{"old":"/api/v1/observations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/observations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/observations/:id","type":0,"val":"observations","end":""},{"old":"/api/v1/observations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['observations.observations.show']['types'],
  },
  'observations.observations.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/observations/:id',
    tokens: [{"old":"/api/v1/observations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/observations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/observations/:id","type":0,"val":"observations","end":""},{"old":"/api/v1/observations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['observations.observations.update']['types'],
  },
  'observations.observations.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/observations/:id',
    tokens: [{"old":"/api/v1/observations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/observations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/observations/:id","type":0,"val":"observations","end":""},{"old":"/api/v1/observations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['observations.observations.destroy']['types'],
  },
  'observations.observations.restore': {
    methods: ["POST"],
    pattern: '/api/v1/observations/:id/restore',
    tokens: [{"old":"/api/v1/observations/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/observations/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/observations/:id/restore","type":0,"val":"observations","end":""},{"old":"/api/v1/observations/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/observations/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['observations.observations.restore']['types'],
  },
  'observations.observations.record_harvest': {
    methods: ["PATCH"],
    pattern: '/api/v1/observations/:id/harvest',
    tokens: [{"old":"/api/v1/observations/:id/harvest","type":0,"val":"api","end":""},{"old":"/api/v1/observations/:id/harvest","type":0,"val":"v1","end":""},{"old":"/api/v1/observations/:id/harvest","type":0,"val":"observations","end":""},{"old":"/api/v1/observations/:id/harvest","type":1,"val":"id","end":""},{"old":"/api/v1/observations/:id/harvest","type":0,"val":"harvest","end":""}],
    types: placeholder as Registry['observations.observations.record_harvest']['types'],
  },
  'observations.attachments.by_observation': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/observations/:observationId/attachments',
    tokens: [{"old":"/api/v1/observations/:observationId/attachments","type":0,"val":"api","end":""},{"old":"/api/v1/observations/:observationId/attachments","type":0,"val":"v1","end":""},{"old":"/api/v1/observations/:observationId/attachments","type":0,"val":"observations","end":""},{"old":"/api/v1/observations/:observationId/attachments","type":1,"val":"observationId","end":""},{"old":"/api/v1/observations/:observationId/attachments","type":0,"val":"attachments","end":""}],
    types: placeholder as Registry['observations.attachments.by_observation']['types'],
  },
  'attachments.attachments.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/attachments',
    tokens: [{"old":"/api/v1/attachments","type":0,"val":"api","end":""},{"old":"/api/v1/attachments","type":0,"val":"v1","end":""},{"old":"/api/v1/attachments","type":0,"val":"attachments","end":""}],
    types: placeholder as Registry['attachments.attachments.index']['types'],
  },
  'attachments.attachments.store': {
    methods: ["POST"],
    pattern: '/api/v1/attachments',
    tokens: [{"old":"/api/v1/attachments","type":0,"val":"api","end":""},{"old":"/api/v1/attachments","type":0,"val":"v1","end":""},{"old":"/api/v1/attachments","type":0,"val":"attachments","end":""}],
    types: placeholder as Registry['attachments.attachments.store']['types'],
  },
  'attachments.attachments.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/attachments/:id',
    tokens: [{"old":"/api/v1/attachments/:id","type":0,"val":"api","end":""},{"old":"/api/v1/attachments/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/attachments/:id","type":0,"val":"attachments","end":""},{"old":"/api/v1/attachments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['attachments.attachments.show']['types'],
  },
  'attachments.attachments.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/attachments/:id',
    tokens: [{"old":"/api/v1/attachments/:id","type":0,"val":"api","end":""},{"old":"/api/v1/attachments/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/attachments/:id","type":0,"val":"attachments","end":""},{"old":"/api/v1/attachments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['attachments.attachments.update']['types'],
  },
  'attachments.attachments.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/attachments/:id',
    tokens: [{"old":"/api/v1/attachments/:id","type":0,"val":"api","end":""},{"old":"/api/v1/attachments/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/attachments/:id","type":0,"val":"attachments","end":""},{"old":"/api/v1/attachments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['attachments.attachments.destroy']['types'],
  },
  'syncQueue.sync_queue.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/sync-queue/stats',
    tokens: [{"old":"/api/v1/sync-queue/stats","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue/stats","type":0,"val":"sync-queue","end":""},{"old":"/api/v1/sync-queue/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.stats']['types'],
  },
  'syncQueue.sync_queue.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/sync-queue',
    tokens: [{"old":"/api/v1/sync-queue","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue","type":0,"val":"sync-queue","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.index']['types'],
  },
  'syncQueue.sync_queue.store': {
    methods: ["POST"],
    pattern: '/api/v1/sync-queue',
    tokens: [{"old":"/api/v1/sync-queue","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue","type":0,"val":"sync-queue","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.store']['types'],
  },
  'syncQueue.sync_queue.batch': {
    methods: ["POST"],
    pattern: '/api/v1/sync-queue/batch',
    tokens: [{"old":"/api/v1/sync-queue/batch","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue/batch","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue/batch","type":0,"val":"sync-queue","end":""},{"old":"/api/v1/sync-queue/batch","type":0,"val":"batch","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.batch']['types'],
  },
  'syncQueue.sync_queue.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/sync-queue/:id',
    tokens: [{"old":"/api/v1/sync-queue/:id","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue/:id","type":0,"val":"sync-queue","end":""},{"old":"/api/v1/sync-queue/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.show']['types'],
  },
  'syncQueue.sync_queue.update_status': {
    methods: ["PATCH"],
    pattern: '/api/v1/sync-queue/:id/status',
    tokens: [{"old":"/api/v1/sync-queue/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue/:id/status","type":0,"val":"sync-queue","end":""},{"old":"/api/v1/sync-queue/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/sync-queue/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.update_status']['types'],
  },
  'syncQueue.sync_queue.retry': {
    methods: ["POST"],
    pattern: '/api/v1/sync-queue/:id/retry',
    tokens: [{"old":"/api/v1/sync-queue/:id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue/:id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue/:id/retry","type":0,"val":"sync-queue","end":""},{"old":"/api/v1/sync-queue/:id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/sync-queue/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.retry']['types'],
  },
  'syncQueue.sync_queue.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/sync-queue/:id',
    tokens: [{"old":"/api/v1/sync-queue/:id","type":0,"val":"api","end":""},{"old":"/api/v1/sync-queue/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/sync-queue/:id","type":0,"val":"sync-queue","end":""},{"old":"/api/v1/sync-queue/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['syncQueue.sync_queue.destroy']['types'],
  },
  'auditLogs.audit_logs.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit-logs/stats',
    tokens: [{"old":"/api/v1/audit-logs/stats","type":0,"val":"api","end":""},{"old":"/api/v1/audit-logs/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/audit-logs/stats","type":0,"val":"audit-logs","end":""},{"old":"/api/v1/audit-logs/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['auditLogs.audit_logs.stats']['types'],
  },
  'auditLogs.audit_logs.by_record': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit-logs/record/:tableName/:recordId',
    tokens: [{"old":"/api/v1/audit-logs/record/:tableName/:recordId","type":0,"val":"api","end":""},{"old":"/api/v1/audit-logs/record/:tableName/:recordId","type":0,"val":"v1","end":""},{"old":"/api/v1/audit-logs/record/:tableName/:recordId","type":0,"val":"audit-logs","end":""},{"old":"/api/v1/audit-logs/record/:tableName/:recordId","type":0,"val":"record","end":""},{"old":"/api/v1/audit-logs/record/:tableName/:recordId","type":1,"val":"tableName","end":""},{"old":"/api/v1/audit-logs/record/:tableName/:recordId","type":1,"val":"recordId","end":""}],
    types: placeholder as Registry['auditLogs.audit_logs.by_record']['types'],
  },
  'auditLogs.audit_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit-logs',
    tokens: [{"old":"/api/v1/audit-logs","type":0,"val":"api","end":""},{"old":"/api/v1/audit-logs","type":0,"val":"v1","end":""},{"old":"/api/v1/audit-logs","type":0,"val":"audit-logs","end":""}],
    types: placeholder as Registry['auditLogs.audit_logs.index']['types'],
  },
  'auditLogs.audit_logs.store': {
    methods: ["POST"],
    pattern: '/api/v1/audit-logs',
    tokens: [{"old":"/api/v1/audit-logs","type":0,"val":"api","end":""},{"old":"/api/v1/audit-logs","type":0,"val":"v1","end":""},{"old":"/api/v1/audit-logs","type":0,"val":"audit-logs","end":""}],
    types: placeholder as Registry['auditLogs.audit_logs.store']['types'],
  },
  'auditLogs.audit_logs.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit-logs/:id',
    tokens: [{"old":"/api/v1/audit-logs/:id","type":0,"val":"api","end":""},{"old":"/api/v1/audit-logs/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/audit-logs/:id","type":0,"val":"audit-logs","end":""},{"old":"/api/v1/audit-logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['auditLogs.audit_logs.show']['types'],
  },
  'imports.imports.store': {
    methods: ["POST"],
    pattern: '/api/v1/imports',
    tokens: [{"old":"/api/v1/imports","type":0,"val":"api","end":""},{"old":"/api/v1/imports","type":0,"val":"v1","end":""},{"old":"/api/v1/imports","type":0,"val":"imports","end":""}],
    types: placeholder as Registry['imports.imports.store']['types'],
  },
  'imports.imports.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/imports',
    tokens: [{"old":"/api/v1/imports","type":0,"val":"api","end":""},{"old":"/api/v1/imports","type":0,"val":"v1","end":""},{"old":"/api/v1/imports","type":0,"val":"imports","end":""}],
    types: placeholder as Registry['imports.imports.index']['types'],
  },
  'imports.imports.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/imports/:id',
    tokens: [{"old":"/api/v1/imports/:id","type":0,"val":"api","end":""},{"old":"/api/v1/imports/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/imports/:id","type":0,"val":"imports","end":""},{"old":"/api/v1/imports/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['imports.imports.show']['types'],
  },
  'imports.imports.schema': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/imports/:id/schema',
    tokens: [{"old":"/api/v1/imports/:id/schema","type":0,"val":"api","end":""},{"old":"/api/v1/imports/:id/schema","type":0,"val":"v1","end":""},{"old":"/api/v1/imports/:id/schema","type":0,"val":"imports","end":""},{"old":"/api/v1/imports/:id/schema","type":1,"val":"id","end":""},{"old":"/api/v1/imports/:id/schema","type":0,"val":"schema","end":""}],
    types: placeholder as Registry['imports.imports.schema']['types'],
  },
  'imports.imports.records': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/imports/:id/records',
    tokens: [{"old":"/api/v1/imports/:id/records","type":0,"val":"api","end":""},{"old":"/api/v1/imports/:id/records","type":0,"val":"v1","end":""},{"old":"/api/v1/imports/:id/records","type":0,"val":"imports","end":""},{"old":"/api/v1/imports/:id/records","type":1,"val":"id","end":""},{"old":"/api/v1/imports/:id/records","type":0,"val":"records","end":""}],
    types: placeholder as Registry['imports.imports.records']['types'],
  },
  'predictions.predictions.ml_health': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/predictions/ml-health',
    tokens: [{"old":"/api/v1/predictions/ml-health","type":0,"val":"api","end":""},{"old":"/api/v1/predictions/ml-health","type":0,"val":"v1","end":""},{"old":"/api/v1/predictions/ml-health","type":0,"val":"predictions","end":""},{"old":"/api/v1/predictions/ml-health","type":0,"val":"ml-health","end":""}],
    types: placeholder as Registry['predictions.predictions.ml_health']['types'],
  },
  'predictions.predictions.store': {
    methods: ["POST"],
    pattern: '/api/v1/predictions',
    tokens: [{"old":"/api/v1/predictions","type":0,"val":"api","end":""},{"old":"/api/v1/predictions","type":0,"val":"v1","end":""},{"old":"/api/v1/predictions","type":0,"val":"predictions","end":""}],
    types: placeholder as Registry['predictions.predictions.store']['types'],
  },
  'predictions.predictions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/predictions',
    tokens: [{"old":"/api/v1/predictions","type":0,"val":"api","end":""},{"old":"/api/v1/predictions","type":0,"val":"v1","end":""},{"old":"/api/v1/predictions","type":0,"val":"predictions","end":""}],
    types: placeholder as Registry['predictions.predictions.index']['types'],
  },
  'predictions.predictions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/predictions/:id',
    tokens: [{"old":"/api/v1/predictions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/predictions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/predictions/:id","type":0,"val":"predictions","end":""},{"old":"/api/v1/predictions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['predictions.predictions.show']['types'],
  },
  'rag.rag.status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/rag/status',
    tokens: [{"old":"/api/v1/rag/status","type":0,"val":"api","end":""},{"old":"/api/v1/rag/status","type":0,"val":"v1","end":""},{"old":"/api/v1/rag/status","type":0,"val":"rag","end":""},{"old":"/api/v1/rag/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['rag.rag.status']['types'],
  },
  'rag.rag.query': {
    methods: ["POST"],
    pattern: '/api/v1/rag/query',
    tokens: [{"old":"/api/v1/rag/query","type":0,"val":"api","end":""},{"old":"/api/v1/rag/query","type":0,"val":"v1","end":""},{"old":"/api/v1/rag/query","type":0,"val":"rag","end":""},{"old":"/api/v1/rag/query","type":0,"val":"query","end":""}],
    types: placeholder as Registry['rag.rag.query']['types'],
  },
  'monetization.monetization.list_products': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/monetization/products',
    tokens: [{"old":"/api/v1/monetization/products","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/products","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/products","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['monetization.monetization.list_products']['types'],
  },
  'monetization.monetization.store_product': {
    methods: ["POST"],
    pattern: '/api/v1/monetization/products',
    tokens: [{"old":"/api/v1/monetization/products","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/products","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/products","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['monetization.monetization.store_product']['types'],
  },
  'monetization.monetization.show_product': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/monetization/products/:id',
    tokens: [{"old":"/api/v1/monetization/products/:id","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/products/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/products/:id","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/products/:id","type":0,"val":"products","end":""},{"old":"/api/v1/monetization/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monetization.monetization.show_product']['types'],
  },
  'monetization.monetization.update_product': {
    methods: ["PATCH"],
    pattern: '/api/v1/monetization/products/:id',
    tokens: [{"old":"/api/v1/monetization/products/:id","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/products/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/products/:id","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/products/:id","type":0,"val":"products","end":""},{"old":"/api/v1/monetization/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monetization.monetization.update_product']['types'],
  },
  'monetization.monetization.list_subscriptions': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/monetization/subscriptions',
    tokens: [{"old":"/api/v1/monetization/subscriptions","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/subscriptions","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/subscriptions","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/subscriptions","type":0,"val":"subscriptions","end":""}],
    types: placeholder as Registry['monetization.monetization.list_subscriptions']['types'],
  },
  'monetization.monetization.store_subscription': {
    methods: ["POST"],
    pattern: '/api/v1/monetization/subscriptions',
    tokens: [{"old":"/api/v1/monetization/subscriptions","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/subscriptions","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/subscriptions","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/subscriptions","type":0,"val":"subscriptions","end":""}],
    types: placeholder as Registry['monetization.monetization.store_subscription']['types'],
  },
  'monetization.monetization.list_transactions': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/monetization/transactions',
    tokens: [{"old":"/api/v1/monetization/transactions","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/transactions","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/transactions","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/transactions","type":0,"val":"transactions","end":""}],
    types: placeholder as Registry['monetization.monetization.list_transactions']['types'],
  },
  'monetization.monetization.chapa_webhook': {
    methods: ["POST"],
    pattern: '/api/v1/monetization/chapa/webhook',
    tokens: [{"old":"/api/v1/monetization/chapa/webhook","type":0,"val":"api","end":""},{"old":"/api/v1/monetization/chapa/webhook","type":0,"val":"v1","end":""},{"old":"/api/v1/monetization/chapa/webhook","type":0,"val":"monetization","end":""},{"old":"/api/v1/monetization/chapa/webhook","type":0,"val":"chapa","end":""},{"old":"/api/v1/monetization/chapa/webhook","type":0,"val":"webhook","end":""}],
    types: placeholder as Registry['monetization.monetization.chapa_webhook']['types'],
  },
  'importTrends': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/import-trends',
    tokens: [{"old":"/api/v1/analytics/import-trends","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/import-trends","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/import-trends","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/import-trends","type":0,"val":"import-trends","end":""}],
    types: placeholder as Registry['importTrends']['types'],
  },
  'yieldTrends': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/yield-trends',
    tokens: [{"old":"/api/v1/analytics/yield-trends","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/yield-trends","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/yield-trends","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/yield-trends","type":0,"val":"yield-trends","end":""}],
    types: placeholder as Registry['yieldTrends']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
